from django.utils.translation import gettext_lazy as _
from django.db import models
from enterprise.models import *
from event.models import *
from purchase_order.models import *

# Create your models here.
class ChooseInvoiceType(models.TextChoices):
    # Refer here for enum https://docs.djangoproject.com/en/3.2/ref/models/fields/#field-choices-enum-types
    PERFORMA = 'performa', _('performa')
    GOODS = 'goods', _('goods')
    FREIGHT = 'freight', _('freight')
    SERVICE = 'service', _('service')

class Invoice(models.Model):
    invoice_id = models.AutoField(primary_key=True, editable=False)
    document_url = models.URLField(null=True, blank=True)
    invoice_type = models.CharField(max_length=100, choices=ChooseInvoiceType.choices, default=ChooseInvoiceType.GOODS)
    created_by_user_id = models.ForeignKey(User, related_name="invoice_created_by_user_id", on_delete=models.CASCADE)
    seller_invoice_id = models.CharField(max_length=100, blank=True)
    provisional_invoice_id = models.CharField(max_length=100, blank=True)
    delivery_document_id = models.CharField(max_length=100, blank=True)
    provisional_document_url = models.URLField(null=True, blank=True)
    purchase_order_id = models.ForeignKey(PurchaseOrder, related_name="invoice_purchase_order_id", on_delete=models.CASCADE)
    buyer_purchase_order_id = models.CharField(max_length=100)
    invoice_creation_datetime = models.DateTimeField(auto_now_add=True)
    seller_id = models.ForeignKey(Seller, related_name="invoice_seller_id", on_delete=models.CASCADE)
    seller_entity_name = models.CharField(max_length=500)
    seller_address_id = models.ForeignKey(Address, related_name="invoice_seller_address_id", on_delete=models.CASCADE)
    seller_contact_user_id = models.ForeignKey(User, related_name="invoice_seller_contact_user_id", on_delete=models.CASCADE)
    seller_contact_name = models.CharField(max_length=100)
    seller_contact_phone = models.CharField(max_length=100, blank=True)
    seller_contact_email = models.EmailField(max_length=100)
    buyer_id = models.ForeignKey(Buyer, related_name="invoice_buyer_id", on_delete=models.CASCADE)
    buyer_entity_name = models.CharField(max_length=100)
    buyer_billing_address_id = models.ForeignKey(Address, related_name="invoice_buyer_billing_address_id", on_delete=models.CASCADE)
    buyer_shipping_address_id = models.ForeignKey(Address, related_name="invoice_buyer_shipping_address_id", on_delete=models.CASCADE)
    buyer_contact_user_id = models.ForeignKey(User, related_name="invoice_buyer_contact_user_id", on_delete=models.CASCADE)
    buyer_contact_name = models.CharField(max_length=100)
    buyer_contact_phone = models.CharField(max_length=100, blank=True)
    buyer_contact_email = models.EmailField(max_length=100)
    invoice_discount_percentage = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    seller_comments = models.TextField(max_length=500, blank=True)
    status = models.CharField(max_length=100, default="issued")
    closing_user_id_seller = models.ForeignKey(User, related_name="invoice_closing_user_id_seller",on_delete=models.CASCADE, null=True)
    closing_comment_seller = models.TextField(max_length=500, blank=True)
    closing_datetime_seller = models.DateTimeField(null=True)
    closing_user_id_buyer = models.ForeignKey(User, related_name="invoice_closing_user_id_buyer",on_delete=models.CASCADE, null=True)
    closing_comment_buyer = models.TextField(max_length=500, blank=True)
    closing_datetime_buyer = models.DateTimeField(null=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    invoice_close_datetime = models.DateTimeField(null=True)

class InvoiceItem(models.Model):
    invoice_line_item_id = models.AutoField(primary_key=True, editable=False)
    invoice_id = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    purchase_order_line_item_id = models.ForeignKey(PurchaseOrderItem, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer_item_id = models.CharField(max_length=100)
    buyer_item_name = models.CharField(max_length=100)
    buyer_item_description = models.TextField(max_length=500, blank=True)
    seller_comments = models.TextField(max_length=500, blank=True)
    measurement_unit_id = models.ForeignKey(MeasurementUnit, on_delete=models.CASCADE)
    rate = models.DecimalField(max_digits=25, decimal_places=10)
    quantity_invoiced = models.DecimalField(max_digits=25, decimal_places=10)
    shipping_per_unit = models.DecimalField(max_digits=25, decimal_places=10)
    amount_invoiced = models.DecimalField(max_digits=25, decimal_places=10)
    amount_due = models.DecimalField(max_digits=25, decimal_places=10)
    amount_paid = models.DecimalField(max_digits=25, decimal_places=10)
    currency_code = models.ForeignKey(CurrencyCode, on_delete=models.CASCADE)
    payment_terms_reference_date_type = models.CharField(max_length=50, blank=True)
    payment_terms_days = models.IntegerField(null=True)
    dispatch_date = models.DateTimeField(null=True)
    receipt_date = models.DateTimeField(null=True)
    payment_due_date = models.DateTimeField()

class InvoiceItemAttribute(models.Model):
    invoice_line_item_id = models.ForeignKey(InvoiceItem, on_delete=models.CASCADE)
    attribute_id = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    attribute_value = models.CharField(max_length=100)

class InvoiceItemCharge(models.Model):
    invoice_line_item_id = models.ForeignKey(InvoiceItem, on_delete=models.CASCADE)
    charge_name = models.CharField(max_length=500)
    charge_type = models.CharField(max_length=100, blank=True)
    charge_percentage = models.DecimalField(max_digits=25, decimal_places=10)

class InvoiceBuyerInformation(models.Model):
    invoice_id = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.CASCADE)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100)

class InvoiceSellerInformation(models.Model):
    invoice_id = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.CASCADE)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100)

class DraftInvoice(models.Model):
    invoice_id = models.AutoField(primary_key=True, editable=False)
    document_url = models.URLField(null=True, blank=True)
    invoice_type = models.CharField(max_length=100, choices=ChooseInvoiceType.choices, default=ChooseInvoiceType.GOODS)
    created_by_user_id = models.ForeignKey(User, related_name="draft_invoice_created_by_user_id", on_delete=models.CASCADE)
    seller_invoice_id = models.CharField(max_length=100, blank=True)
    provisional_invoice_id = models.CharField(max_length=100, blank=True)
    delivery_document_id = models.CharField(max_length=100, blank=True)
    provisional_document_url = models.URLField(null=True, blank=True)
    purchase_order_id = models.ForeignKey(PurchaseOrder, related_name="draft_invoice_purchase_order_id", on_delete=models.CASCADE)
    buyer_purchase_order_id = models.CharField(max_length=100, blank=True)
    invoice_creation_datetime = models.DateTimeField(auto_now_add=True)
    seller_id = models.ForeignKey(Seller, related_name="draft_invoice_seller_id", on_delete=models.CASCADE)
    seller_entity_name = models.CharField(max_length=500, blank=True)
    seller_address_id = models.ForeignKey(Address, null= True, related_name="draft_invoice_seller_address_id", on_delete=models.CASCADE)
    seller_contact_user_id = models.ForeignKey(User, null=True, related_name="draft_invoice_seller_contact_user_id", on_delete=models.CASCADE)
    seller_contact_name = models.CharField(max_length=100, blank=True)
    seller_contact_phone = models.CharField(max_length=100, blank=True)
    seller_contact_email = models.EmailField(max_length=100,blank=True)
    buyer_id = models.ForeignKey(Buyer, related_name="draft_invoice_buyer_id", on_delete=models.CASCADE)
    buyer_entity_name = models.CharField(max_length=100, blank=True)
    buyer_billing_address_id = models.ForeignKey(Address, null=True, related_name="draft_invoice_buyer_billing_address_id", on_delete=models.CASCADE)
    buyer_shipping_address_id = models.ForeignKey(Address, null=True, related_name="draft_invoice_buyer_shipping_address_id", on_delete=models.CASCADE)
    buyer_contact_user_id = models.ForeignKey(User, null =True, related_name="draft_invoice_buyer_contact_user_id", on_delete=models.CASCADE)
    buyer_contact_name = models.CharField(max_length=100, blank=True)
    buyer_contact_phone = models.CharField(max_length=100, blank=True)
    buyer_contact_email = models.EmailField(max_length=100, blank=True)
    invoice_discount_percentage = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    seller_comments = models.TextField(max_length=500, blank=True)
    status = models.CharField(max_length=100, default="issued")
    closing_user_id_seller = models.ForeignKey(User, related_name="draft_invoice_closing_user_id_seller",on_delete=models.CASCADE, null=True)
    closing_comment_seller = models.TextField(max_length=500, blank=True)
    closing_datetime_seller = models.DateTimeField(null=True)
    closing_user_id_buyer = models.ForeignKey(User, related_name="draft_invoice_closing_user_id_buyer",on_delete=models.CASCADE, null=True)
    closing_comment_buyer = models.TextField(max_length=500, blank=True)
    closing_datetime_buyer = models.DateTimeField(null=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    invoice_close_datetime = models.DateTimeField(null=True)

class DraftInvoiceItem(models.Model):
    invoice_line_item_id = models.AutoField(primary_key=True, editable=False)
    invoice_id = models.ForeignKey(DraftInvoice, on_delete=models.CASCADE)
    purchase_order_line_item_id = models.ForeignKey(PurchaseOrderItem, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer_item_id = models.CharField(max_length=100, blank=True)
    buyer_item_name = models.CharField(max_length=100, blank=True)
    buyer_item_description = models.TextField(max_length=500, blank=True)
    seller_comments = models.TextField(max_length=500, blank=True)
    measurement_unit_id = models.ForeignKey(MeasurementUnit, null=True, on_delete=models.CASCADE)
    rate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    quantity_invoiced = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    shipping_per_unit = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    amount_invoiced = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    amount_due = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    amount_paid = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    currency_code = models.ForeignKey(CurrencyCode, on_delete=models.CASCADE, null=True)
    payment_terms_reference_date_type = models.CharField(max_length=50, blank=True)
    payment_terms_days = models.IntegerField(null=True)
    dispatch_date = models.DateTimeField(null=True)
    receipt_date = models.DateTimeField(null=True)
    payment_due_date = models.DateTimeField(null=True)

class DraftInvoiceItemAttribute(models.Model):
    invoice_line_item_id = models.ForeignKey(DraftInvoiceItem, on_delete=models.CASCADE)
    attribute_id = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    attribute_value = models.CharField(max_length=100, blank=True)

class DraftInvoiceItemCharge(models.Model):
    invoice_line_item_id = models.ForeignKey(DraftInvoiceItem, on_delete=models.CASCADE)
    charge_name = models.CharField(max_length=500)
    charge_type = models.CharField(max_length=100, blank=True)
    charge_percentage = models.DecimalField(max_digits=25, decimal_places=10, null=True)

class DraftInvoiceBuyerInformation(models.Model):
    invoice_id = models.ForeignKey(DraftInvoice, on_delete=models.CASCADE)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.CASCADE)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100, blank=True)

class DraftInvoiceSellerInformation(models.Model):
    invoice_id = models.ForeignKey(DraftInvoice, on_delete=models.CASCADE)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.CASCADE)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100, blank=True)

class ProformaInvoice(models.Model):
    invoice_id = models.AutoField(primary_key=True, editable=False)
    purchase_order_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    buyer_purchase_order_id = models.CharField(max_length=100)
    document_url = models.URLField(null=True, blank=True)
    created_by_user_id = models.ForeignKey(User, related_name="proforma_invoice_created_by_user_id", on_delete=models.CASCADE)
    invoice_creation_datetime = models.DateTimeField(auto_now_add=True)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    seller_comments = models.TextField(max_length=500, blank=True)
    status = models.CharField(max_length=100)
    currency_code = models.ForeignKey(CurrencyCode, on_delete=models.CASCADE)
    amount_invoiced = models.DecimalField(max_digits=25, decimal_places=10)
    amount_paid = models.DecimalField(max_digits=25, decimal_places=10)
    closing_user_id_seller = models.ForeignKey(User, related_name="proforma_invoice_closing_user_id_seller",on_delete=models.CASCADE, null=True)
    closing_comment_seller = models.TextField(max_length=500, blank=True)
    closing_datetime_seller = models.DateTimeField(null=True)
    closing_user_id_buyer = models.ForeignKey(User, related_name="proforma_invoice_closing_user_id_buyer",on_delete=models.CASCADE, null=True)
    closing_comment_buyer = models.TextField(max_length=500, blank=True)
    closing_datetime_buyer = models.DateTimeField(null=True)
    invoice_close_datetime = models.DateTimeField(null=True)