# Generated by Django 3.1.7 on 2021-07-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address_nickname', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('full_address', models.TextField(blank=True)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('address3', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_or_territory', models.CharField(max_length=100, null=True)),
                ('postal_code', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100, unique=True)),
                ('attribute_value_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerItem',
            fields=[
                ('entry_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('buyer_item_id', models.CharField(max_length=100)),
                ('buyer_item_name', models.CharField(max_length=100)),
                ('buyer_item_description', models.TextField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterprise_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('enterprise_name', models.CharField(max_length=500, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=500)),
                ('entity_primary_address', models.TextField()),
                ('entity_primary_email', models.EmailField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500, unique=True)),
                ('item_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('measurement_unit_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('measurement_unit_primary_name', models.CharField(max_length=100, unique=True)),
                ('measurement_unit_category', models.CharField(max_length=100)),
                ('measurement_unit_value_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(max_length=100)),
                ('user_phonenumber', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enterprise.entity')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enterprise.entity')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.item')),
                ('measurement_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.measurementunit')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerItemAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=100)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.attribute')),
                ('buyer_item_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.buyeritem')),
            ],
        ),
        migrations.AddField(
            model_name='buyeritem',
            name='enterprise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise'),
        ),
        migrations.AddField(
            model_name='buyeritem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.item'),
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.module')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.user')),
            ],
            options={
                'unique_together': {('user_id', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.entity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.user')),
            ],
            options={
                'unique_together': {('user_id', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.attribute')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.item')),
            ],
            options={
                'unique_together': {('item_id', 'attribute_id')},
            },
        ),
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_billing_address', models.BooleanField(default=False)),
                ('is_shipping_address', models.BooleanField(default=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.address')),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.entity')),
            ],
            options={
                'ordering': ['entity_id', 'order_id', 'address_id'],
                'unique_together': {('entity_id', 'address_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='buyeritem',
            unique_together={('enterprise_id', 'buyer_item_id')},
        ),
        migrations.CreateModel(
            name='AttributeValueOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.attribute')),
            ],
            options={
                'unique_together': {('attribute_id', 'value')},
            },
        ),
        migrations.CreateModel(
            name='BuyerSellerRelationship',
            fields=[
                ('relationship_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('buyer_enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
                ('buyer_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.buyer')),
                ('seller_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.seller')),
            ],
            options={
                'unique_together': {('buyer_enterprise_id', 'buyer_entity_id', 'seller_entity_id')},
            },
        ),
    ]
