# Generated by Django 3.1.7 on 2021-07-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('goods_receipt_entry_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('buyer_goods_receipt_id', models.CharField(max_length=100)),
                ('receipt_datetime', models.DateTimeField(auto_now_add=True)),
                ('receiving_user_name', models.CharField(max_length=100)),
                ('receiving_user_phone', models.CharField(blank=True, max_length=100)),
                ('receiving_user_email', models.EmailField(max_length=100)),
                ('delivered_quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('receipt_quantity_rejected', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('receipt_quantity_accepted', models.DecimalField(decimal_places=10, max_digits=25)),
                ('problem_category', models.CharField(blank=True, max_length=100)),
                ('problem_picture_id', models.IntegerField(null=True)),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('deleted_datetime', models.DateTimeField(null=True)),
                ('invoice_line_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceitem')),
                ('measurement_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.measurementunit')),
                ('receiving_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.user')),
            ],
        ),
    ]
