# Generated by Django 3.1.7 on 2021-07-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('goods_receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('quality_check_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document_url', models.URLField(blank=True, max_length=100, null=True)),
                ('buyer_analytical_report_number', models.CharField(blank=True, max_length=100)),
                ('created_by_name', models.CharField(max_length=100)),
                ('created_by_phone', models.CharField(blank=True, max_length=100)),
                ('created_by_email', models.EmailField(max_length=100)),
                ('quality_check_datetime', models.DateTimeField(auto_now_add=True)),
                ('quality_check_category', models.CharField(choices=[('regular', 'regular'), ('production line', 'production line')], default='regular', max_length=100)),
                ('quality_check_reason', models.CharField(blank=True, max_length=100)),
                ('quantity_rejected', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('problem_category', models.CharField(blank=True, max_length=100)),
                ('problem_picture_id', models.IntegerField(null=True)),
                ('problem_comments', models.TextField(blank=True, max_length=500)),
                ('created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check_created_by_user_id', to='enterprise.user')),
                ('goods_receipt_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_receipt.goodsreceipt')),
                ('measurement_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.measurementunit')),
            ],
        ),
    ]
