from django.db import models
from enterprise.models import *
from event.models import *
# Create your models here.

class PurchaseOrder(models.Model):
    purchase_order_id = models.AutoField(primary_key=True, editable=False)
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    purchase_order_creation_datetime = models.DateTimeField(auto_now_add=True)
    buyer_id = models.ForeignKey(Buyer, related_name="Buyer", on_delete=models.CASCADE)
    buyer_purchase_order_id = models.CharField(max_length=100)
    buyer_entity_name = models.CharField(max_length=100)
    buyer_billing_address_id = models.ForeignKey(Address, related_name="buyer_billing_address_id", on_delete=models.CASCADE)
    buyer_shipping_address_id = models.ForeignKey(Address, related_name="buyer_shipping_address_id", on_delete=models.CASCADE)
    buyer_approver_user_id = models.ForeignKey(User, related_name="buyer_approver_user_id", on_delete=models.CASCADE)
    buyer_approver_name = models.CharField(max_length=100)
    buyer_contact_user_id = models.ForeignKey(User, related_name="buyer_contact_user_id", on_delete=models.CASCADE)
    buyer_contact_name = models.CharField(max_length=100)
    buyer_contact_phone = models.CharField(max_length=100, blank=True)
    buyer_contact_email = models.EmailField(max_length=100)
    is_freight_purchase_order = models.BooleanField(default=False)
    seller_id = models.ForeignKey(Seller, related_name="Seller", on_delete=models.CASCADE)
    seller_entity_name = models.CharField(max_length=100)
    seller_address_id = models.ForeignKey(Address, related_name="seller_address_id", on_delete=models.CASCADE)
    seller_contact_user_id = models.ForeignKey(User, related_name="seller_contact_user_id", on_delete=models.CASCADE)
    seller_contact_name = models.CharField(max_length=100)
    seller_contact_phone = models.CharField(max_length=100, blank=True)
    seller_contact_email = models.EmailField(max_length=100)
    seller_acknowledgement_user_id = models.ForeignKey(User, related_name="seller_acknowledgement_user_id", on_delete=models.SET_NULL, null=True)
    seller_acknowledgement_datetime = models.DateTimeField(null=True)
    delivery_schedule_type = models.CharField(max_length=500, blank=True)
    payment_terms_code = models.CharField(max_length=500, blank=True)    
    purchase_order_discount_percentage = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    buyer_comments = models.TextField(max_length=500, blank=True)
    status = models.CharField(max_length=100, default="issued")
    reissue_draft_purchase_order_id = models.IntegerField(null=True)
    reissue_purchase_order_id = models.IntegerField(null=True)
    closing_user_id_buyer = models.ForeignKey(User, related_name="closing_user_id_buyer_id", on_delete=models.SET_NULL, null=True)
    closing_comment_buyer = models.TextField(max_length=500, blank=True)
    closing_datetime_buyer = models.DateTimeField(null=True)
    closing_user_id_seller = models.ForeignKey(User, related_name="closing_user_id_seller_id", on_delete=models.SET_NULL, null=True)
    closing_comment_seller = models.TextField(max_length=500, blank=True)
    closing_datetime_seller = models.DateTimeField(null=True)
    modified_datetime = models.DateTimeField(null=True)
    purchase_order_close_datetime = models.DateTimeField(null=True)

    class Meta:
        unique_together = ("buyer_id", "buyer_purchase_order_id",)

class PurchaseOrderItem(models.Model):
    purchase_order_line_item_id = models.AutoField(primary_key=True, editable=False)
    purchase_order_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer_item_id = models.CharField(max_length=100)
    buyer_item_name = models.CharField(max_length=100)
    buyer_item_description = models.TextField(max_length=500, blank=True)
    due_date = models.DateTimeField(null=True)
    currency_code = models.ForeignKey(CurrencyCode, on_delete=models.CASCADE)
    measurement_unit_id = models.ForeignKey(MeasurementUnit, related_name="purchase_order_item_measurement_unit_id", on_delete=models.CASCADE)
    rate = models.DecimalField(max_digits=25, decimal_places=10)
    quantity = models.DecimalField(max_digits=25, decimal_places=10)
    max_acceptable_quantity = models.DecimalField(max_digits=25, decimal_places=10)
    measurement_unit_alternate_id = models.ForeignKey(MeasurementUnit, related_name="measurement_unit_alternate_id", on_delete=models.SET_NULL, null=True)
    rate_alternate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    quantity_alternate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    taxes_and_charges_percentage = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    taxes_and_charges_value = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    total_order_value = models.DecimalField(max_digits=25, decimal_places=10)
    shipping_per_unit = models.DecimalField(max_digits=25, decimal_places=10, default=0)

class PurchaseOrderItemCharge(models.Model):
    purchase_order_line_item_id = models.ForeignKey(PurchaseOrderItem, on_delete=models.CASCADE)
    charge_name = models.CharField(max_length=500)
    charge_type = models.CharField(max_length=100, blank=True)
    charge_percentage = models.DecimalField(max_digits=25, decimal_places=10, default=0)

    class Meta:
        unique_together = ("purchase_order_line_item_id", "charge_name",)

class PurchaseOrderItemAttribute(models.Model):
    purchase_order_line_item_id = models.ForeignKey(PurchaseOrderItem, on_delete=models.CASCADE)
    attribute_id = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    attribute_value = models.CharField(max_length=500)

class EntityIdentification(models.Model):
    identification_id = models.AutoField(primary_key=True, editable=False)
    entity_id = models.ForeignKey(Entity, on_delete=models.CASCADE)
    identification_name = models.CharField(max_length=100)
    identification_category = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100)
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    deleted_datetime = models.DateTimeField(null=True)

class EntityPurchaseOrderDefaultIdentification(models.Model):
    entity_id = models.ForeignKey(Entity, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.CASCADE)

class PurchaseOrderBuyerInformation(models.Model):
    purchase_order_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.SET_NULL, null=True)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100)

class PurchaseOrderSellerInformation(models.Model):
    purchase_order_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.SET_NULL, null=True)
    identification_name = models.CharField(max_length=100)
    identification_value = models.CharField(max_length=100)

class DraftPurchaseOrder(models.Model):
    purchase_order_id = models.AutoField(primary_key=True, editable=False)
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    purchase_order_creation_datetime = models.DateTimeField(auto_now_add=True)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE)
    buyer_purchase_order_id = models.CharField(max_length=100, blank=True)
    buyer_entity_name = models.CharField(max_length=100)
    buyer_billing_address_id = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, related_name="buyer_billing_address")
    buyer_shipping_address_id = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, related_name="buyer_shipping_address")
    buyer_approver_user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="buyer_approver_user")
    buyer_approver_name = models.CharField(max_length=100, blank=True)
    buyer_contact_user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_contact_user")
    buyer_contact_name = models.CharField(max_length=100, blank=True)
    buyer_contact_phone = models.CharField(max_length=100, blank=True)
    buyer_contact_email = models.EmailField(max_length=100, blank=True, null=True)
    is_freight_purchase_order = models.BooleanField(default=False)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE)
    seller_entity_name = models.CharField(max_length=100)
    seller_address_id = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, related_name="seller_address")
    seller_contact_user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="seller_contact_user")
    seller_contact_name = models.CharField(max_length=100, blank=True)
    seller_contact_phone = models.CharField(max_length=100, blank=True)
    seller_contact_email = models.EmailField(max_length=100, blank=True, null=True)
    seller_acknowledgement_user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="seller_acknowledgement_user")
    seller_acknowledgement_datetime = models.DateTimeField(null=True)
    delivery_schedule_type = models.CharField(max_length=100, blank=True)
    payment_terms_code = models.CharField(max_length=100, blank=True)
    purchase_order_discount_percentage = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    buyer_comments = models.TextField(max_length=500, blank=True)
    status = models.CharField(max_length=100, default="draft")
    reissue_draft_purchase_order_id = models.IntegerField(null=True)
    reissue_purchase_order_id = models.IntegerField(null=True)
    closing_user_id_buyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="closing_user_buyer")
    closing_comment_buyer = models.TextField(max_length=500, blank=True)
    closing_datetime_buyer = models.DateTimeField(null=True)
    closing_user_id_seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="closing_user_seller")
    closing_comment_seller = models.TextField(max_length=500, blank=True)
    closing_datetime_seller = models.DateTimeField(null=True)
    purchase_order_close_datetime = models.DateTimeField(null=True)
    modified_datetime = models.DateTimeField(auto_now=True)

class DraftPurchaseOrderItem(models.Model):
    purchase_order_line_item_id = models.AutoField(primary_key=True, editable=False)
    purchase_order_id = models.ForeignKey(DraftPurchaseOrder, on_delete=models.CASCADE)
    item_id = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer_item_id = models.CharField(max_length=100, blank=True)
    buyer_item_name = models.CharField(max_length=100, blank=True)
    buyer_item_description = models.TextField(max_length=500, blank=True)
    due_date = models.DateTimeField(null=True)
    currency_code = models.ForeignKey(CurrencyCode, on_delete=models.SET_NULL, null=True)
    measurement_unit_id = models.ForeignKey(MeasurementUnit, on_delete=models.SET_NULL, null=True, related_name="measurement_unit")
    rate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    quantity = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    max_acceptable_quantity = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    measurement_unit_alternate_id = models.ForeignKey(MeasurementUnit, on_delete=models.SET_NULL, null=True, related_name="measurement_unit_alternate")
    shipping_per_unit = models.DecimalField(max_digits=25, decimal_places=10, default=0)
    rate_alternate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    quantity_alternate = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    taxes_and_charges_percentage = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    taxes_and_charges_value = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    total_order_value = models.DecimalField(max_digits=25, decimal_places=10, null=True)
    modified_datetime = models.DateTimeField(auto_now=True)

class DraftPurchaseOrderItemCharge(models.Model):
    purchase_order_line_item_id = models.ForeignKey(DraftPurchaseOrderItem, on_delete=models.CASCADE)
    charge_name = models.CharField(max_length=100, blank=True)
    charge_type = models.CharField(max_length=100, blank=True)
    charge_percentage = models.DecimalField(max_digits=25, decimal_places=10, null=True)

class DraftPurchaseOrderItemAttribute(models.Model):
    purchase_order_line_item_id = models.ForeignKey(DraftPurchaseOrderItem, on_delete=models.CASCADE)
    attribute_id = models.ForeignKey(Attribute, on_delete=models.CASCADE, null=True)
    attribute_value = models.CharField(max_length=500, blank=True)

class DraftPurchaseOrderBuyerInformation(models.Model):
    purchase_order_id = models.ForeignKey(DraftPurchaseOrder, on_delete=models.CASCADE)
    buyer_id = models.ForeignKey(Buyer, on_delete=models.CASCADE, null=True)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.SET_NULL, null=True)
    identification_name = models.CharField(max_length=100, blank=True)
    identification_value = models.CharField(max_length=100, blank=True)

class DraftPurchaseOrderSellerInformation(models.Model):
    purchase_order_id = models.ForeignKey(DraftPurchaseOrder, on_delete=models.CASCADE)
    seller_id = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True)
    identification_id = models.ForeignKey(EntityIdentification, on_delete=models.SET_NULL, null=True)
    identification_name = models.CharField(max_length=100, blank=True)
    identification_value = models.CharField(max_length=100, blank=True)

class PurchaseOrderKeyMapping(models.Model):
    purchase_order_id = models.OneToOneField(PurchaseOrder, on_delete=models.CASCADE)
    draft_purchase_order_id = models.OneToOneField(DraftPurchaseOrder, on_delete=models.CASCADE)