from event.views.event_view import draft_event
from event.views.event_view import draft_event_list
from event.views.event_view import draft_event_item_info
from event.views.event_view import draft_event_item_attribute
from event.views.event_view import draft_event_item_seller
from event.views.event_view import draft_event_item
from event.views.event_view import draft_event_item_list
from event.views.event_view import key_mapping
from event.views.event_view import draft_event_shift_event
from event.views.event_view import event_review_page
from event.views.event_view import event
from event.views.event_view import event_seller_status_change
from event.views.event_view import shift_event_draft_event
from event.views.bid import draft_bid_info
from event.views.bid import draft_bid_info_list
from event.views.bid import draft_bid_item
from event.views.bid import draft_bid_item_tax
from event.views.bid import draft_bid
from event.views.bid import draft_bid_list
from event.views.bid import draft_bid_shift_bid
from event.views.bid import bid_info
from event.views.bid import bid_info_list
from event.views.bid import bid_item
from event.views.bid import bid_item_list
from event.views.bid import bid_item_tax
from event.views.bid import bid
from event.views.bid import bid_list
from event.views.bid import lastest_bid
from event.views.bid import seller_bid_history
from event.views.bid import buyer_bid_history
from event.views.award import hello
from event.views.award import buyer_event_tab_count
from event.views.award import buyer_event_draft_tab
from event.views.award import buyer_event_ongoing_tab
from event.views.award import buyer_event_finished_tab
from event.views.award import seller_event_tab_count
from event.views.award import seller_event_invited_tab
from event.views.award import seller_event_ongoing_tab
from event.views.award import seller_event_decision_tab
from event.views.award import award
from event.views.award import award_new_version
from event.views.award import award_list
from event.views.award import draft_award_list
from event.views.award import draft_award_list_shift_award
from event.views.award import award_history
from event.views.award import decline_award