from django.urls import path, re_path
from enterprise import views

app_name = "enterprise"
urlpatterns = [
    path('hello', views.hello.as_view(), name="hello"),
    path("enterprise/<int:enterprise_id>", views.enterprise.as_view(), name="enterprise"),
    path("enterprise", views.enterprise_list.as_view(), name="enterprise_list"),
    path("user/<int:user_id>", views.enterprise_user.as_view(), name="user"),
    path("enterprise_user/<int:enterprise_id>", views.enterprise_user_list.as_view(), name="enterprise_user_list"),
    path("entity/<int:entity_id>", views.enterprise_entity.as_view(), name="entity"),
    path("enterprise_entity/<int:enterprise_id>", views.enterprise_entity_list.as_view(), name="enterprise_entity_list"),
    path("user_entity/<int:user_id>", views.user_entity_list.as_view(), name="get_user_entity_list"),
    path("user_entity/<int:user_id>/<int:entity_id>", views.user_entity_list.as_view(), name="post_user_entity"),
    path("seller", views.seller_list.as_view(), name="get_seller_list"),
    path("seller/<int:entity_id>", views.seller_list.as_view(), name="post_seller"),
    path("buyer", views.buyer_list.as_view(), name="get_buyer_list"),
    path("buyer/<int:entity_id>", views.buyer_list.as_view(), name="post_buyer"),
    path("buyer_seller_relationship/<int:buyer_id>", views.buyer_seller_relationship_list.as_view(), name="get_buyer_seller_relationship_list"),
    path("buyer_seller_relationship/<int:buyer_id>/<int:seller_id>", views.buyer_seller_relationship_list.as_view(), name="buyer_seller_relationship_list"),
    path("module", views.module_list.as_view(), name="get_module_list"),
    path("module/<int:module_id>", views.module.as_view(), name="module"),
    path("user_module/<int:user_id>", views.user_module_list.as_view(), name="get_user_module_list"),
    path("user_module/<int:user_id>/<int:module_id>", views.user_module_list.as_view(), name="user_module_list"),
    path("attribute", views.attribute_list.as_view(), name="get_attribute_list"),
    path("attribute/<int:attribute_id>", views.attribute.as_view(), name="attribute"),
    path("attribute_value_option/<int:attribute_id>", views.attribute_value_option_list.as_view(), name="attribute_value_option"),
    path("item/<int:item_id>", views.item.as_view(), name="item"),
    path("item", views.item_list.as_view(), name="item_list"),
    path("item_attribute/<int:item_id>", views.item_attribute_list.as_view(), name="get_item_attribute_list"),
    path("item_attribute/<int:item_id>/<int:attribute_id>", views.item_attribute_list.as_view(), name="item_attribute"),
    path("buyer_item/<int:entry_id>", views.buyer_item.as_view(), name="buyer_item"),
    path("enterprise_buyer_item/<int:enterprise_id>", views.buyer_item_list.as_view(), name="buyer_item_list"),
    path("buyer_item_attribute_value/<int:entry_id>", views.buyer_item_attribute_value_list.as_view(), name="buyer_item_attribute_value_list"),
    path("currency_code", views.currency_code.as_view(), name="currency_code"),
    path("currency_code/<str:currency_code_name>", views.currency_code.as_view(), name="delete_currency_code"),
    path("measurement_unit" , views.measurement_unit_list.as_view(), name ="measurement_unit"),
    path("measurement_unit/<int:measurement_unit_id>", views.measurement_unit.as_view(), name ="get_measurement_unit"),
    path("item_measurement_unit", views.item_measurement_unit_list.as_view(), name ="item_measurement_unit"),
    path("item_measurement_unit/<int:item_id>", views.item_measurement_unit.as_view(), name ="get_item_measurement_unit"),
    path("item_measurement_unit/<int:item_id>/<int:measurement_unit_id>", views.item_measurement_unit.as_view(), name ="delete_item_measurement_unit"),
    path("address/<int:address_id>", views.address.as_view(), name="get_address"),
    path("address", views.address_list.as_view(), name="address_list"),
    path("entity_address/<int:entity_id>", views.entity_address.as_view(), name="get_entity_address"),
    path("entity_address", views.entity_address_list.as_view(), name="entity_address"),
    path("countries", views.country_list.as_view(), name = "countries"),
    path("search_keyword_buyer_items_result/<int:user_id>/<slug:keyword>", views.search_keyword_buyer_items_result.as_view(), name="search_keyword_buyer_items_result"),
]
